package databaseclass.finalproject.dao;

import databaseclass.finalproject.entity.User1;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface User1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_1
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_1
     *
     * @mbg.generated
     */
    int insert(User1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_1
     *
     * @mbg.generated
     */
    User1 selectByPrimaryKey(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_1
     *
     * @mbg.generated
     */
    List<User1> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_1
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(User1 record);
}