package databaseclass.finalproject.entity;

import java.io.Serializable;
import java.util.Date;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Null;
import javax.validation.constraints.Size;

import com.alibaba.fastjson.annotation.JSONField;

/**
 * @author QinKuai
 * 创建时间：2019年12月11日
 * 描述：
 * 用户的实体
 * 添加校验标签能简化数据校验工作
 */
public class User implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbg.generated
     */
	@NotNull
	@Size(min = 1, max = 20)
	@JSONField
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_password
     *
     * @mbg.generated
     */
	@NotNull
	@Size(min = 6, max = 16)
	@JSONField(serialize = false)
    private String uPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_sex
     *
     * @mbg.generated
     */
	@JSONField(name = "sex")
    private String uSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_birthday
     *
     * @mbg.generated
     */
	@JSONField(name = "birthday")
    private Date uBirthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_registertime
     *
     * @mbg.generated
     */
    @Null
    @JSONField(serialize = false)
    private Date uRegistertime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_email
     *
     * @mbg.generated
     */
    @NotNull
    @JSONField(name = "email")
    private String uEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_rank
     *
     * @mbg.generated
     */
    @Null
    @JSONField(name = "rank")
    private Short uRank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_type
     *
     * @mbg.generated
     */
    @Null
    @JSONField(name = "type")
    private String uType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_exp
     *
     * @mbg.generated
     */
    @Null
    @JSONField(name = "exp")
    private Integer uExp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_point
     *
     * @mbg.generated
     */
    @Null
    @JSONField(name = "point")
    private Integer uPoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_password
     *
     * @return the value of user.u_password
     *
     * @mbg.generated
     */
    public String getuPassword() {
        return uPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_password
     *
     * @param uPassword the value for user.u_password
     *
     * @mbg.generated
     */
    public void setuPassword(String uPassword) {
        this.uPassword = uPassword == null ? null : uPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_sex
     *
     * @return the value of user.u_sex
     *
     * @mbg.generated
     */
    public String getuSex() {
        return uSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_sex
     *
     * @param uSex the value for user.u_sex
     *
     * @mbg.generated
     */
    public void setuSex(String uSex) {
        this.uSex = uSex == null ? null : uSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_birthday
     *
     * @return the value of user.u_birthday
     *
     * @mbg.generated
     */
    public Date getuBirthday() {
        return uBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_birthday
     *
     * @param uBirthday the value for user.u_birthday
     *
     * @mbg.generated
     */
    public void setuBirthday(Date uBirthday) {
        this.uBirthday = uBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_registertime
     *
     * @return the value of user.u_registertime
     *
     * @mbg.generated
     */
    public Date getuRegistertime() {
        return uRegistertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_registertime
     *
     * @param uRegistertime the value for user.u_registertime
     *
     * @mbg.generated
     */
    public void setuRegistertime(Date uRegistertime) {
        this.uRegistertime = uRegistertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_email
     *
     * @return the value of user.u_email
     *
     * @mbg.generated
     */
    public String getuEmail() {
        return uEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_email
     *
     * @param uEmail the value for user.u_email
     *
     * @mbg.generated
     */
    public void setuEmail(String uEmail) {
        this.uEmail = uEmail == null ? null : uEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_rank
     *
     * @return the value of user.u_rank
     *
     * @mbg.generated
     */
    public Short getuRank() {
        return uRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_rank
     *
     * @param uRank the value for user.u_rank
     *
     * @mbg.generated
     */
    public void setuRank(Short uRank) {
        this.uRank = uRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_type
     *
     * @return the value of user.u_type
     *
     * @mbg.generated
     */
    public String getuType() {
        return uType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_type
     *
     * @param uType the value for user.u_type
     *
     * @mbg.generated
     */
    public void setuType(String uType) {
        this.uType = uType == null ? null : uType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_exp
     *
     * @return the value of user.u_exp
     *
     * @mbg.generated
     */
    public Integer getuExp() {
        return uExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_exp
     *
     * @param uExp the value for user.u_exp
     *
     * @mbg.generated
     */
    public void setuExp(Integer uExp) {
        this.uExp = uExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_point
     *
     * @return the value of user.u_point
     *
     * @mbg.generated
     */
    public Integer getuPoint() {
        return uPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_point
     *
     * @param uPoint the value for user.u_point
     *
     * @mbg.generated
     */
    public void setuPoint(Integer uPoint) {
        this.uPoint = uPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", username=").append(username);
        sb.append(", password=").append(uPassword);
        sb.append(", uSex=").append(uSex);
        sb.append(", uBirthday=").append(uBirthday);
        sb.append(", uRegistertime=").append(uRegistertime);
        sb.append(", uEmail=").append(uEmail);
        sb.append(", uRank=").append(uRank);
        sb.append(", uType=").append(uType);
        sb.append(", uExp=").append(uExp);
        sb.append(", uPoint=").append(uPoint);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}